# Generated by Django 3.2.9 on 2021-11-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211125_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='charmod',
            name='leben',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='charmod',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
