# Generated by Django 3.2.9 on 2021-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20211125_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='charmod',
            name='besigtegegner',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='charmod',
            name='charEP',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='charmod',
            name='charLevel',
            field=models.IntegerField(null=True),
        ),
    ]
